Repository AY2324S2-CS2113T-T09-2/tp, pull requests merged in 2024-04, with the labels that each got.

#144 Implement sorting funtionality to list command
  src/main/java/seedu/binbash/command/DeleteCommand.java
  src/main/java/seedu/binbash/command/ListCommand.java
  src/main/java/seedu/binbash/comparators/ItemComparatorByCostPrice.java
  src/main/java/seedu/binbash/comparators/ItemComparatorByExpiryDate.java
  src/main/java/seedu/binbash/comparators/ItemComparatorBySalePrice.java
  src/main/java/seedu/binbash/enums/SortOptionEnum.java
  src/main/java/seedu/binbash/inventory/ItemList.java
  src/main/java/seedu/binbash/parser/CommandOptionAdder.java
  src/main/java/seedu/binbash/parser/ListCommandParser.java
  src/main/java/seedu/binbash/parser/Parser.java
  src/test/java/seedu/binbash/command/ListCommandTest.java
  src/test/java/seedu/binbash/comparators/ItemComparatorByCostPriceTest.java
  src/test/java/seedu/binbash/comparators/ItemComparatorByExpiryDateTest.java
  src/test/java/seedu/binbash/comparators/ItemComparatorBySalePriceTest.java
  src/test/java/seedu/binbash/parser/ListCommandParserTest.java
Labels: type.Task, priority.High

#154 Update UserGuide.md for `add` feature
  docs/UserGuide.md
Labels: priority.High

#160 Simple changes to wording of guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#166 Fix `update` and `add` to catch exceptions
  src/main/java/seedu/binbash/command/RestockCommand.java
  src/main/java/seedu/binbash/command/SellCommand.java
  src/main/java/seedu/binbash/exceptions/InvalidArgumentException.java
  src/main/java/seedu/binbash/exceptions/InvalidFormatException.java
  src/main/java/seedu/binbash/inventory/ItemList.java
  src/main/java/seedu/binbash/parser/AddCommandParser.java
  src/main/java/seedu/binbash/parser/Parser.java
  src/main/java/seedu/binbash/parser/UpdateCommandParser.java
Labels: priority.High, severity.High

#169 Update DG Search Implementation
  docs/DeveloperGuide.md
  docs/diagrams/SearchAssistantReferenceFrameDiagram.puml
  docs/diagrams/SearchAssistantSequenceDiagram.puml
  docs/images/SearchAssistantReferenceFrameDiagram.png
  docs/images/SearchAssistantSequenceDiagram.png
Labels: priority.High

#170 Update UG - Horizontal rules and links back to table of contents at end of each section
  docs/UserGuide.md
Labels: type.Task, priority.High

#175 Fix sell and restock
  docs/UserGuide.md
  src/main/java/seedu/binbash/command/RestockCommand.java
  src/main/java/seedu/binbash/command/SellCommand.java
  src/main/java/seedu/binbash/inventory/ItemList.java
  src/main/java/seedu/binbash/parser/AddCommandParser.java
  src/main/java/seedu/binbash/parser/DeleteCommandParser.java
  src/main/java/seedu/binbash/parser/ListCommandParser.java
  src/main/java/seedu/binbash/parser/Parser.java
  src/main/java/seedu/binbash/parser/RestockCommandParser.java
  src/main/java/seedu/binbash/parser/SearchCommandParser.java
  src/main/java/seedu/binbash/parser/SellCommandParser.java
  src/main/java/seedu/binbash/parser/UpdateCommandParser.java
Labels: priority.High, severity.High

#180 Fix bug that crashes program when deleting items already deleted
  src/main/java/seedu/binbash/inventory/ItemList.java
Labels: type.Bug, severity.High

#181 Update UG for v2.0
  docs/UserGuide.md
Labels: type.Task, priority.High

#186 Update List and Delete sections of Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  src/main/java/seedu/binbash/command/DeleteCommand.java
  src/main/java/seedu/binbash/command/ListCommand.java
Labels: type.Task, priority.High

#249 Update UG/DG to indicate that delete iten_name is case-sensitive
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#256 More expressive command error messages
  src/main/java/seedu/binbash/command/RestockCommand.java
  src/main/java/seedu/binbash/command/SellCommand.java
  src/main/java/seedu/binbash/exceptions/InvalidArgumentException.java
  src/main/java/seedu/binbash/exceptions/InvalidFormatException.java
  src/main/java/seedu/binbash/inventory/ItemList.java
  src/main/java/seedu/binbash/parser/AddCommandParser.java
  src/main/java/seedu/binbash/parser/Parser.java
  src/main/java/seedu/binbash/parser/RestockCommandParser.java
  src/main/java/seedu/binbash/parser/SearchCommandParser.java
  src/main/java/seedu/binbash/parser/SellCommandParser.java
  src/main/java/seedu/binbash/parser/UpdateCommandParser.java
  src/test/java/seedu/binbash/command/RestockCommandTest.java
  src/test/java/seedu/binbash/command/SellCommandTest.java
  src/test/java/seedu/binbash/parser/ParserTest.java
  src/test/java/seedu/binbash/parser/RestockCommandParserTest.java
  src/test/java/seedu/binbash/parser/SellCommandParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#261 Fix several issues and bugs discovered from PE-D
  docs/UserGuide.md
  src/main/java/seedu/binbash/inventory/ItemList.java
  src/main/java/seedu/binbash/item/OperationalItem.java
  src/main/java/seedu/binbash/parser/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High

#270 Add Images for Getting Started - Windows section of UG
  docs/UserGuide.md
  docs/images/WindowsCd.png
  docs/images/WindowsCmd.png
  docs/images/WindowsRun.png
Labels: type.Task, priority.High

#275 Improve Program Defensiveness
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ParserClassDiagram.puml
  docs/images/ParserClassDiagram.png
  docs/images/fedora_sway_terminal.png
  src/main/java/seedu/binbash/BinBash.java
  src/main/java/seedu/binbash/command/ByeCommand.java
  src/main/java/seedu/binbash/parser/AddCommandParser.java
  src/main/java/seedu/binbash/parser/CommandOptionAdder.java
  src/main/java/seedu/binbash/parser/DeleteCommandParser.java
  src/main/java/seedu/binbash/parser/ListCommandParser.java
  src/main/java/seedu/binbash/parser/Parser.java
  src/main/java/seedu/binbash/parser/RestockCommandParser.java
  src/main/java/seedu/binbash/parser/SearchCommandParser.java
  src/main/java/seedu/binbash/parser/SellCommandParser.java
  src/main/java/seedu/binbash/parser/UpdateCommandParser.java
  src/main/java/seedu/binbash/ui/Ui.java
  src/test/java/seedu/binbash/parser/ParserTest.java
  src/test/java/seedu/binbash/parser/SearchCommandParserTest.java
Labels: priority.High
