Repository AY2324S2-CS2113T-T09-2/tp, pull requests merged in 2024-03, with the labels that each got.

#61 Implement delete item by item name funtionality
  src/main/java/seedu/binbash/ItemList.java
  src/main/java/seedu/binbash/Parser.java
  src/main/java/seedu/binbash/command/DeleteIndexCommand.java
  src/main/java/seedu/binbash/command/DeleteNameCommand.java
  src/test/java/seedu/binbash/ItemListTest.java
Labels: type.Task, priority.High

#74 Implement delete by name funtionality
  src/main/java/seedu/binbash/ItemList.java
  src/main/java/seedu/binbash/Parser.java
  src/main/java/seedu/binbash/command/DeleteCommand.java
  src/test/java/seedu/binbash/ItemListTest.java
  src/test/java/seedu/binbash/ParserTest.java
  src/test/java/seedu/binbash/command/DeleteCommandTest.java
Labels: type.Task, priority.High

#84 Update delete/add section of UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#86 Update 'search' and 'list' portion of UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#95 Incorporate jline library
  build.gradle
  src/main/java/seedu/binbash/ui/Ui.java
  src/test/java/seedu/binbash/BinBashTest.java
Labels: type.Enhancement, priority.Medium

#100 Add restock and sell features
  src/main/java/seedu/binbash/Item.java
  src/main/java/seedu/binbash/ItemList.java
  src/main/java/seedu/binbash/Parser.java
  src/main/java/seedu/binbash/command/RestockCommand.java
  src/main/java/seedu/binbash/command/SellCommand.java
Labels: type.Task, priority.High

#107 Implement logging class to write logs in txt file
  .gitignore
  logs/logs.txt
  src/main/java/seedu/binbash/BinBash.java
  src/main/java/seedu/binbash/ItemList.java
  src/main/java/seedu/binbash/logger/BinBashLogger.java
Labels: type.Enhancement, priority.High

#119 Update developer guide with logging, target user profile and value proposition sections
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#123 Update developer guide with delete item section
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#133 Add JavaDocs for Delete/DeleteCommand/BinBashLogger methods, Update Logging, Add new DeleteCommand tests.
  src/main/java/seedu/binbash/ItemList.java
  src/main/java/seedu/binbash/command/AddCommand.java
  src/main/java/seedu/binbash/command/ByeCommand.java
  src/main/java/seedu/binbash/command/Command.java
  src/main/java/seedu/binbash/command/DeleteCommand.java
  src/main/java/seedu/binbash/command/ListCommand.java
  src/main/java/seedu/binbash/command/RestockCommand.java
  src/main/java/seedu/binbash/command/SearchCommand.java
  src/main/java/seedu/binbash/command/SellCommand.java
  src/main/java/seedu/binbash/logger/BinBashLogger.java
  src/main/java/seedu/binbash/storage/Storage.java
  src/test/java/seedu/binbash/command/DeleteCommandTest.java
Labels: type.Task, priority.High
